<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\File;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionsGenerateCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'apipermissions:generate';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate permissions from API routes used by role';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        // get routes with matched criteria
        $routes = [];
        foreach (Route::getRoutes()->getRoutesByName() as $key => $route) {
            if (strpos($route->uri, 'api/') !== false && in_array('auth.basic:admin', $route->action['middleware'])) {
                $routes[] = $route->action['as'];
            }
        }
        $totalRoutes = count($routes);
        $user = \App\Models\Admin::find(1);
        if (!$user) {
            return $this->error("Admin with userid 1 not found. run artisan admin:generate first");
        }
        
        $roleName = 'Compatibility Role - Auto Generated';
        $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'api', 'description' => 'Auto Generated by Console CBMS']);
        $genratedPermissions = [];
        foreach ($routes as $route) {
            // TODO: maybe nambah group permission?
            $permission = Permission::firstOrCreate(['name' => $route, 'guard_name' => 'api']);
            if (!$role->hasPermissionTo($route)) {
                $role->givePermissionTo($route);
                $genratedPermissions[] = $permission->name;
            }
            if (!$user->hasRole($roleName)) {
                $user->assignRole($role);
            }
        }

        // TODO: membuat UI buat API Role dan attach rolenya ke admin

        $totalGenratedPermissions = count($genratedPermissions);

        return $this->info("{$totalGenratedPermissions} permissions successfully generated");
    }
}
