<?php
namespace App\Module;

use DB;
use App\Helpers\LogActivity;
use App\Helpers\Cfg;

use App\Models\Server as ServerModel;
use App\Models\Hosting;
use App\Models\Hostingaddon;

use Illuminate\Support\Facades\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\App;

/**
 * Merged server module and function
 *
 * 1. WHMCS\Module\Server
 * 2. WHMCS\Module\AbstractModule
 * 3. modulefunction.php
 */
class Server
{
  // Server module
  protected $type = "server";
  protected $serviceID = "";
  protected $addonId = 0;
  protected $serviceModule = "";
  protected $addonModule = "";
  protected $modelData = NULL;
  protected $params = NULL;

  // Abstract module
  protected $loadedmodule = "";
  protected $metaData = array();
  protected $moduleParams = array();
  protected $usesDirectories = true;
  protected $cacheActiveModules = NULL;
  const TYPE_ADMIN = "admin";
  const TYPE_ADDON = "addons";
  const TYPE_FRAUD = "fraud";
  const TYPE_GATEWAY = "gateways";
  const TYPE_NOTIFICATION = "notifications";
  const TYPE_REGISTRAR = "registrars";
  const TYPE_REPORT = "reports";
  const TYPE_SECURITY = "security";
  const TYPE_SERVER = "servers";
  const TYPE_SOCIAL = "social";
  const TYPE_SUPPORT = "support";
  const TYPE_WIDGET = "widgets";
  const ALL_TYPES = NULL;
  const FUNCTIONDOESNTEXIST = "!Function not found in module!";

  // Module function

  public static function factoryFromModel($model)
    {
        $self = new self();
        if ($model instanceof Hostingaddon) {
            $self->addonId = $model->id;
            $self->modelData = $model->load("productAddon", "productAddon.moduleConfiguration", "productAddon.customFields", "service", "service.product", "service.product.customFields", "client");
            $self->serviceID = $model->serviceId;
            $self->load($self->getModuleByAddonId());
        } else {
            $self->serviceID = $model->id;
            $self->modelData = $model->load("product", "client");
            $self->load($self->getModuleByServiceID());
        }
        return $self;
    }

    public function generateRandomPasswordForModule()
    {
        $randomGenerator = new \App\Helpers\Random();
        $moduleSpecialChars = $this->getMetaDataValue("PasswordGenerationSpecialCharacters");
        if (trim($moduleSpecialChars)) {
            $randomGenerator->setSymbols($moduleSpecialChars);
        }
        $passwordFormat = Cfg::get("AutoGeneratedPasswordFormat");
        if ($passwordFormat == "legacy") {
            return $randomGenerator->string(4, 2, 4, 0);
        }
        $lowercase = 4;
        $uppercase = 4;
        $numbers = 4;
        $symbols = 2;
        return $randomGenerator->string($lowercase, $uppercase, $numbers, $symbols);
    }

  /**
   * getModuleType
   */
  public function getModuleType($id)
  {
    $data = ServerModel::find($id);
    $type = $data->type;
    return $type;
  }

  public function ModuleBuildParams($serviceID, $addonId = 0)
  {
    if ($addonId) {
      if (!$this->loadByAddonId($addonId)) {
        LogActivity::Save("Required Product Module '" . $this->getAddonModule() . "' Missing");
      }
    } else {
      if (!$this->loadByServiceID($serviceID)) {
        LogActivity::Save("Required Product Module '" . $this->getServiceModule() . "' Missing");
      }
    }
    return $this->buildParams();
  }

  public function ModuleCallFunction($function, $serviceID, $extraParams = array(), $addonId = 0)
  {
    if ($addonId && !$this->loadByAddonId($addonId)) {
      if (!$this->getAddonModule()) {
        return "success";
      }
      LogActivity::Save("Required Product Module '" . $this->getAddonModule() . "' Missing");
      return "Module Not Found";
    }
    if (!$addonId && !$this->loadByServiceID($serviceID)) {
      if (!$this->getServiceModule()) {
        return "success";
      }
      LogActivity::Save("Required Product Module '" . $this->getServiceModule() . "' Missing");
      return "Module Not Found";
    }
    $params = $this->buildParams();
    if (is_array($extraParams)) {
      $params = array_merge($params, $extraParams);
    }
    $serviceid = (int) $params["serviceid"];
    $userid = (int) $params["userid"];

    $hookabort = false;
    $hookresults = \App\Helpers\Hooks::run_hook("PreModule" . $function, array("params" => $params));
    $hookabort = false;
    foreach ($hookresults as $hookvals) {
      foreach ($hookvals as $k => $v) {
        if ($k == "abortcmd" && $v === true) {
          $hookabort = true;
          $result = "Function Aborted by Action Hook Code";
        }
      }
      if (!$hookabort) {
        $params = array_replace_recursive($params, $hookvals);
      }
    }

    $entityType = "service";
    $entityId = $serviceID;
    $entityModule = $this->getServiceModule();
    $serviceOrAddon = "Service ID: " . $serviceID;
    $extraSaveData = array();
    if ($addonId) {
      $entityType = "addon";
      $entityId = $addonId;
      $entityModule = $this->getAddonModule();
      $serviceOrAddon = "Addon ID: " . $addonId;
    }
    $logname = $function;
    if ($logname == "ChangePackage") {
      $logname = "Change Package";
    } else {
      if ($logname == "ChangePassword") {
        $logname = "Change Password";
      }
    }

    if (!$hookabort) {
      $modfuncname = in_array($function, array("Create", "Suspend", "Unsuspend", "Terminate")) ? $function . "Account" : $function;
      if ($this->functionExists($modfuncname)) {
        try {
          $result = $this->call($modfuncname, $params);
        } catch (\Exception $e) {
          $result = $e->getMessage();
        }

        if ($result == "success") {
          $extra_log_info = $suspendReason = "";
          if ($function == "Suspend") {
            $suspendReason = "";
            if (isset($params["suspendreason"]) && $params["suspendreason"] != "Overdue on Payment") {
              $suspendReason = $params["suspendreason"];
            }
            if ($suspendReason) {
              $extra_log_info = " - Reason: " . $suspendReason;
            }
          }
          LogActivity::Save("Module " . $logname . " Successful" . $extra_log_info . " - " . $serviceOrAddon, $userid);
          $updatearray = array();
          if ($function == "Create") {
            $updatearray = array("domainstatus" => "Active", "termination_date" => "0000-00-00");
            if ($entityType == "addon") {
              $updatearray = array("status" => "Active", "termination_date" => "0000-00-00");
            }
          } else {
            if ($function == "Suspend") {
              $updatearray = array("domainstatus" => "Suspended", "suspendreason" => $suspendReason);
              if ($entityType == "addon") {
                $updatearray = array("status" => "Suspended");
                $extraSaveData["suspend_reason"] = $suspendReason;
              }
            } else {
              if ($function == "Unsuspend") {
                $updatearray = array("domainstatus" => "Active", "suspendreason" => "", "termination_date" => "0000-00-00");
                if ($entityType == "addon") {
                  $updatearray = array("status" => "Active", "termination_date" => "0000-00-00");
                  $extraSaveData["suspend_reason"] = "";
                }
              } else {
                if ($function == "Terminate") {
                  if ($entityType == "addon") {
                    $updatearray = array("status" => "Terminated");
                    if (in_array(DB::table("tblhostingaddons")->where("id", "=", $entityId)->value("termination_date"), array("0000-00-00", "1970-01-01"))) {
                      $updatearray["termination_date"] = date("Y-m-d");
                    }
                  } else {
                    $updatearray = array("domainstatus" => "Terminated");
                    if (in_array(DB::table("tblhosting")->where("id", "=", $serviceid)->value("termination_date"), array("0000-00-00", "1970-01-01"))) {
                      $updatearray["termination_date"] = date("Y-m-d");
                    }
                    $addons = Hostingaddon::where("hostingid", "=", $serviceid)->whereIn("status", array("Active", "Suspended"))->get();
                    foreach ($addons as $addon) {
                      if ($addon->productAddon->module) {
                        \App\Helpers\AddonAutomation::factory($addon)->runAction("TerminateAccount");
                      } else {
                        $addon->status = "Terminated";
                        $addon->termination_date = WHMCS\Carbon::now()->toDateString();
                        $addon->save();
                        \App\Helpers\Hooks::run_hook("AddonTerminated", array("id" => $addon->id, "userid" => $addon->clientId, "serviceid" => $addon->serviceId, "addonid" => $addon->addonId));
                      }
                    }
                  }
                }
              }
            }
          }
          if (0 < count($updatearray)) {
            $table = $entityType == "addon" ? "tblhostingaddons" : "tblhosting";
            DB::table($table)->where('id', $entityId)->update($updatearray);
            if ($extraSaveData) {
            }
          }
          if ($this->isApplicationLinkSupported() && $server->isApplicationLinkingEnabled()) {
            // TODO: doSingleApplicationLinkCall
            // try {
            //   $errors = $server->doSingleApplicationLinkCall("Create");
            //   if (is_array($errors) && 0 < count($errors)) {
            //     logActivity("Application Link Provisioning returned the following warnings: " . implode(", ", $errors));
            //   }
            // } catch (WHMCS\Exception $e) {
            //   logActivity("Application Link Provisioning Failed: " . $e->getMessage() . " - " . $serviceOrAddon);
            // }
          }
          \App\Helpers\Hooks::run_hook("AfterModule" . $function, array("params" => $params));
          \App\Models\Modulequeue::resolve($entityType, $entityId, $entityModule, $modfuncname);
          return "success";
        }
        \App\Models\Modulequeue::add($entityType, $entityId, $entityModule, $modfuncname, $result);
        \App\Helpers\Hooks::run_hook("AfterModule" . $function . "Failed", array("failureResponseMessage" => $result, "params" => $params));
      } else {
        $result = "Function Not Supported by Module";
        if ($function == "Renew") {
          return $result;
        }
      }
    }

    LogActivity::Save("Module " . $logname . " Failed - " . $serviceOrAddon . " - Error: " . $result, $userid);
    return $result;
  }

  public function createServerUsername($domain)
  {
    if (!$domain && !Cfg::get("GenerateRandomUsername")) {
      return "";
    }

    if (!Cfg::get("GenerateRandomUsername")) {
      $domain = strtolower($domain);
      $username = preg_replace("/[^a-z]/", "", $domain);
      $username = substr($username, 0, 8);
      $result = Hosting::select(DB::raw('COUNT(*) as total'))->where('username', $username)->first();
      $data = $result->toArray();
      $username_exists = $data['total'];
      $suffix = 0;
      while (0 < $username_exists) {
        $suffix++;
        $trimlength = 8 - strlen($suffix);
        $username = substr($username, 0, $trimlength) . $suffix;
        $result = Hosting::select(DB::raw('COUNT(*) as total'))->where('username', $username)->first();
        $data = $result->toArray();
        $username_exists = $data['total'];
      }
    } else {
      $lowercase = "abcdefghijklmnopqrstuvwxyz";
      $str = "";
      $seeds_count = strlen($lowercase) - 1;
      for ($i = 0; $i < 8; $i++) {
          $str .= $lowercase[rand(0, $seeds_count)];
      }
      $username = "";
      for ($i = 0; $i < 8; $i++) {
          $randomnum = rand(0, strlen($str) - 1);
          $username .= $str[$randomnum];
          $str = substr($str, 0, $randomnum) . substr($str, $randomnum + 1);
      }
      $result = Hosting::select(DB::raw('COUNT(*) as total'))->where('username', $username)->first();
      $data = $result->toArray();
      $username_exists = $data['total'];
      while (0 < $username_exists) {
          $username = "";
          $str = "";
          for ($i = 0; $i < 8; $i++) {
              $str .= $lowercase[rand(0, $seeds_count)];
          }
          for ($i = 0; $i < 8; $i++) {
              $randomnum = rand(0, strlen($str) - 1);
              $username .= $str[$randomnum];
              $str = substr($str, 0, $randomnum) . substr($str, $randomnum + 1);
          }
          $result = Hosting::select(DB::raw('COUNT(*) as total'))->where('username', $username)->first();
          $data = $result->toArray();
          $username_exists = $data['total'];
      }
    }
    return $username;
  }

  public function ServerCreateAccount($serviceID, $addonId = 0)
  {
    $params = $this->ModuleBuildParams($serviceID, $addonId);
    $updateInfo = array();
    if (array_key_exists("service", $params)) {
      if (!$params["username"]) {
        $params["username"] = $params["service"]["username"];
        $updateInfo["username"] = $params["username"];
      }
      if (!$params["domain"]) {
        $params["domain"] = $params["service"]["domain"];
        $updateInfo["domain"] = $params["domain"];
      }
    }

    if (isset($params["username"]) && !$params["username"]) {
      $usernamegenhook = collect(\App\Helpers\Hooks::run_hook("OverrideModuleUsernameGeneration", $params));
      $username = "";
      if (count($usernamegenhook->filter()->all())) {
        foreach ($usernamegenhook as $usernameval) {
          if (is_string($usernameval)) {
            $username = $usernameval;
          }
        }
      }

      if (!$username) {
        $username = $this->createServerUsername($params["domain"]);
      }
      $updateInfo["username"] = $username;
    }

    if (isset($params["password"]) && !$params["password"]) {
      $updateInfo["password"] = (new \App\Helpers\Pwd())->encrypt(self::generateRandomPassword());
    }

    $moduleMetaData = array();
    if ($this->functionExists("MetaData")) {
      $moduleMetaData = $this->call("MetaData");
    }

    if (!array_key_exists("AutoGenerateUsernameAndPassword", $moduleMetaData) || $moduleMetaData["AutoGenerateUsernameAndPassword"] !== false) {
      if ($updateInfo && !$addonId) {
        DB::table('tblhosting')->where("id", $serviceID)->update($updateInfo);
      } else {
        if ($updateInfo) {
          if (array_key_exists("password", $updateInfo)) {
            $updateInfo["password"] = (new \App\Helpers\Pwd())->decrypt($updateInfo["password"]);
          }
          $params["model"]->serviceProperties->save($updateInfo);
        }
      }
    }

    try {
      return $this->ModuleCallFunction("Create", $serviceID, array(), $addonId);
    } catch (\Exception $e) {
      return $e->getMessage();
    }
  }

  public function ServerSuspendAccount($serviceID, $suspendreason = "", $addonId = 0)
  {
    $extraParams = array("suspendreason" => $suspendreason ? $suspendreason : "Overdue on Payment");
    return $this->ModuleCallFunction("Suspend", $serviceID, $extraParams, $addonId);
  }

  public function ServerUnsuspendAccount($serviceID, $addonId = 0)
  {
    return $this->ModuleCallFunction("Unsuspend", $serviceID, array(), $addonId);
  }

  public function ServerTerminateAccount($serviceID, $addonId = 0)
  {
    return $this->ModuleCallFunction("Terminate", $serviceID, array(), $addonId);
  }

  public function ServerRenew($serviceID, $addonId = 0)
  {
    $result = $this->ModuleCallFunction("Renew", $serviceID, array(), $addonId);
    if ($result == "Function Not Supported by Module") {
      $result = "notsupported";
    }
    return $result;
  }

  public function ServerChangePassword($serviceID, $addonId = 0)
  {
    return $this->ModuleCallFunction("ChangePassword", $serviceID, array(), $addonId);
  }

  public function ServerLoginLink($serviceID, $addonId = 0)
  {
    if ($addonId) {
      $this->loadByAddonId($addonId);
    } else {
      $this->loadByServiceID($serviceID);
    }
    if ($this->functionExists("LoginLink")) {
      return $this->call("LoginLink");
    }
    return "";
  }

  public function ServerChangePackage($serviceID, $addonId = 0)
  {
    return $this->ModuleCallFunction("ChangePackage", $serviceID, array(), $addonId);
  }

  public function ServerCustomFunction($serviceID, $func_name, $addonId = 0)
  {
    if ($addonId) {
      $this->loadByAddonId($addonId);
    } else {
      $this->loadByServiceID($serviceID);
    }
    return $this->call($func_name, array());
  }

  public function ServerClientArea($serviceID, $addonId = 0)
  {
    if ($addonId) {
      $this->loadByAddonId($addonId);
    } else {
      $this->loadByServiceID($serviceID);
    }
    if ($this->functionExists("ClientArea")) {
      return $this->call("ClientArea");
    }
    return "";
  }

  public function ServerUsageUpdate()
  {
    $servers = ServerModel::where("disabled", "0")->orderBy("name", "ASC")->get();
    $updatedServerIds = array();
    foreach ($servers as $serverModel) {
      $this->load($serverModel->type);
      if ($this->functionExists("UsageUpdate")) {
        $updatedServerIds[] = $serverModel->id;
        $response = $this->call("UsageUpdate", $this->getServerParams($serverModel));
        if ($response && !in_array($response, array("success", self::FUNCTIONDOESNTEXIST))) {
          LogActivity::Save("Server Usage Update Failed: " . $response . " - Server ID: " . $serverModel->id);
        }
      }
    }
    return $updatedServerIds;
  }

  // Server module

  public function setServiceId($serviceId, $populateModel = true)
  {
    $this->serviceID = (int) $serviceId;
    $this->params = null;
    if ($populateModel) {
      $this->modelData = Hosting::with("product", "client")->find($serviceId);
    }
    return $this;
  }

  public function setAddonId($addonId)
  {
    $this->addonId = $addonId;
    $this->params = null;
    if ($addonId) {
      $this->modelData = Hostingaddon::with("productAddon", "productAddon.moduleConfiguration", "productAddon.customFields", "service", "service.product", "service.product.customFields", "client")->find($addonId);
      $this->setServiceId($this->modelData->serviceId, false);
    }
    return $this;
  }

  public function getModuleByServiceID($serviceID = 0)
  {
    if ($serviceID) {
      $this->setServiceId($serviceID);
    }
    if (!$serviceID) {
      $serviceID = $this->serviceID;
    }
    if (!$serviceID) {
      return "";
    }
    $this->serviceModule = $this->modelData->product->module;
    return $this->serviceModule;
  }

  public function getModuleByAddonId($addonId = 0)
  {
    if ($addonId) {
      $this->setAddonId($addonId);
    }
    if (!$addonId) {
      $addonId = $this->addonId;
    }
    if (!$addonId) {
      return "";
    }
    if ($this->modelData->productAddon) {
        $this->addonModule = $this->modelData->productAddon->module;
        return $this->addonModule;
    }
    return "";
  }

  public function getServiceModule()
  {
    return $this->serviceModule;
  }

  public function getAddonModule()
  {
    return $this->addonModule;
  }

  public function loadByServiceID($serviceID)
  {
    $this->setServiceId($serviceID);
    $moduleName = $this->getModuleByServiceID();
    return $this->load($moduleName);
  }

  public function loadByAddonId($addonId)
  {
    $this->setAddonId($addonId);
    $moduleName = $this->getModuleByAddonId();
    return $this->load($moduleName);
  }

  public function buildParams()
  {
    if (is_array($this->params)) {
      $params = $this->params;
      $params = array_merge($params, $this->getServerParams($params["serverid"]));
      $this->params = $params;
      $GLOBALS["moduleparams"] = $params;
      return $params;
    }
    $serviceId = (int) $this->serviceID;
    $addonId = $this->addonId;

    if (!$addonId) {
      try {
        $modelData = $this->modelData;
        if (!$modelData) {
          $modelData = Hosting::with("product", "client")->findOrFail($serviceId);
        }
      } catch (\Exception $e) {
        return [];
      }

      $params = [];
      try {
          $params = $this->buildServiceParams($modelData);
      } catch (\Exception $th) {
          //throw $th;
      }
      $params = array_merge($params, $this->getServerParams($modelData->serverId));
    } else {
      try {
        $modelData = $this->modelData;
        if (!$modelData || !$modelData instanceof \App\Models\Hostingaddon) {
          $modelData = Hostingaddon::with("productAddon", "productAddon.moduleConfiguration", "service", "client")->findOrFail($addonId);
        }
      } catch (\Exception $e) {
        return [];
      }
      $params = $this->buildAddonParams($modelData);
      $params = array_merge($params, $this->getServerParams($modelData->serverId));
      $params["service"] = $this->buildServiceParams($modelData->service);
      $params["service"] = array_merge($params, $this->getServerParams($modelData->service->serverId));
    }
    $client = new \App\Helpers\ClientClass($modelData->client);
    $clientsdetails = $client->getDetails();
    $clientsdetails["state"] = $clientsdetails["statecode"];
    if (!array_key_exists("original", $params)) {
      //TODO: $clientsdetails = foreignChrReplace($clientsdetails);
      $params["clientsdetails"] = $clientsdetails;
    }
    $GLOBALS["moduleparams"] = $params;
    $this->params = $params;
    return $params;
  }

  public function getServerParams($server)
  {
    if (is_numeric($server)) {
      $server = ServerModel::find($server);
    }
    if ($server instanceof \App\Models\Server) {
      $params = array(
            "server" => true,
            "serverid" => (int) $server->id,
            "serverip" => $server->ipaddress,
            "serverhostname" => $server->hostname,
            "serverusername" => \App\Helpers\Sanitize::decode($server->username),
            "serverpassword" => \App\Helpers\Sanitize::decode((new \App\Helpers\Pwd())->decrypt($server->password)),
            "serveraccesshash" => \App\Helpers\Sanitize::decode($server->accesshash),
            "serversecure" => (bool) $server->secure,
            "serverhttpprefix" => "http" . ($server->secure ? "s" : ""),
        );
      $portNum = $server->port;
      if (!$portNum) {
        $portNum = $this->getMetaDataValue("Default" . ($server->secure ? "" : "Non") . "SSLPort");
      }
      $params["serverport"] = $portNum;
    } else {
      $params = array("server" => false, "serverip" => "", "serverhostname" => "", "serverusername" => "", "serverpassword" => "", "serveraccesshash" => "", "serversecure" => false, "serverhttpprefix" => "", "serverport" => "");
    }
    return $params;
  }

  protected function buildServiceParams(Hosting $serviceData)
  {
    $serviceId = $serviceData->id;
    $userId = $serviceData->clientId;
    $domain = $serviceData->domain;
    $username = $serviceData->username;
    $password = $serviceData->password;
    $pid = $serviceData->packageId;
    $serverId = $serviceData->serverId;
    $status = $serviceData->domainStatus;
    $params = array();
    $params["accountid"] = $serviceId;
    $params["serviceid"] = $serviceId;
    $params["addonId"] = 0;
    $params["userid"] = $userId;
    $params["domain"] = $domain;
    $params["username"] = $username;
    $params["password"] = \App\Helpers\Sanitize::decode((new \App\Helpers\Pwd)->decrypt($password));
    $params["packageid"] = $pid;
    $params["pid"] = $pid;
    $params["serverid"] = $serverId;
    $params["status"] = $status;
    $params["type"] = $serviceData->product->type;
    $params["producttype"] = $serviceData->product->type;
    $params["moduletype"] = $serviceData->product->module;
    if (!$params["moduletype"]) {
      return array();
    }
    $module = \Module::find($params["moduletype"]);
    if (!$module) {
      throw new \App\Exceptions\Module\NotServicable("Invalid Server Module Name");
    }
    $counter = 1;
    while ($counter <= 24) {
      $variable = "configoption" . $counter;
      $params["configoption" . $counter] = $serviceData->product->{$variable};
      $counter += 1;
    }

    $customFieldsTable = (new \App\Models\Customfield)->getTableName();
    $customFieldsValueTable = (new \App\Models\Customfieldsvalue)->getTableName();
    // $customFields = DB::table("{$customFieldsTable}")->join("{$customFieldsValueTable}", "{$customFieldsValueTable}.fieldid", "=", "{$customFieldsTable}.id")->where("{$customFieldsValueTable}.relid", "=", $serviceId)->where("{$customFieldsTable}.relid", "=", $pid)->where("{$customFieldsTable}.type", "=", "product")->pluck("{$customFieldsValueTable}.value", "{$customFieldsTable}.fieldname")->toArray();
    $customFields = DB::table("tblcustomfields")->join("tblcustomfieldsvalues", "tblcustomfieldsvalues.fieldid", "=", "tblcustomfields.id")->where("tblcustomfieldsvalues.relid", "=", $serviceId)->where("tblcustomfields.relid", "=", $pid)->where("tblcustomfields.type", "=", "product")->pluck("tblcustomfieldsvalues.value", "tblcustomfields.fieldname")->toArray();
    foreach ($customFields as $fieldName => $fieldValue) {
      unset($customFields[$fieldName]);
      if (strpos($fieldName, "|")) {
        $parts = explode("|", $fieldName);
        $fieldName = trim($parts[0]);
      }
      if (strpos($fieldValue, "|")) {
        $parts = explode("|", $fieldValue);
        $fieldValue = trim($parts[0]);
      }
      $customFields[$fieldName] = $fieldValue;
    }
    $params["customfields"] = $customFields;

    $ProductconfigoptionTable = (new \App\Models\Productconfigoption)->getTableName();
    $HostingconfigoptionTable = (new \App\Models\Hostingconfigoption)->getTableName();
    $ProductconfigoptionssubTable = (new \App\Models\Productconfigoptionssub)->getTableName();
    $ProductconfiglinkTable = (new \App\Models\Productconfiglink)->getTableName();
    $configOptions = [];
    // $configOptionsData = DB::table("{$ProductconfigoptionTable}")->join("{$HostingconfigoptionTable}", "{$ProductconfigoptionTable}.id", "=", "{$HostingconfigoptionTable}.configid")->join("{$ProductconfigoptionssubTable}", "{$ProductconfigoptionssubTable}.id", "=", "{$HostingconfigoptionTable}.optionid")->join("{$ProductconfiglinkTable}", "{$ProductconfiglinkTable}.gid", "=", "{$ProductconfigoptionTable}.gid")->where("{$HostingconfigoptionTable}.relid", "=", $serviceId)->where("{$ProductconfiglinkTable}.pid", "=", $pid)->get(array("{$ProductconfigoptionTable}.optionname as productConfigOptionName", "{$ProductconfigoptionTable}.optiontype", "{$ProductconfigoptionssubTable}.optionname", "{$HostingconfigoptionTable}.qty"));
    $configOptionsData = DB::table("tblproductconfigoptions")->join("tblhostingconfigoptions", "tblproductconfigoptions.id", "=", "tblhostingconfigoptions.configid")->join("tblproductconfigoptionssub", "tblproductconfigoptionssub.id", "=", "tblhostingconfigoptions.optionid")->join("tblproductconfiglinks", "tblproductconfiglinks.gid", "=", "tblproductconfigoptions.gid")->where("tblhostingconfigoptions.relid", "=", $serviceId)->where("tblproductconfiglinks.pid", "=", $pid)->get(array("tblproductconfigoptions.optionname as productConfigOptionName", "tblproductconfigoptions.optiontype", "tblproductconfigoptionssub.optionname", "tblhostingconfigoptions.qty"));
    foreach ($configOptionsData as $configOptionData) {
      $configOptionName = $configOptionData->productConfigOptionName;
      $configOptionType = (int) $configOptionData->optiontype;
      $configOptionValue = $configOptionData->optionname;
      $configOptionQuantity = $configOptionData->qty;
      if (strpos($configOptionName, "|")) {
        $configOptionName = explode("|", $configOptionName);
        $configOptionName = trim($configOptionName[0]);
      }
      if (strpos($configOptionValue, "|")) {
        $configOptionValue = explode("|", $configOptionValue);
        $configOptionValue = trim($configOptionValue[0]);
      }
      if (in_array($configOptionType, array(3, 4))) {
        $configOptionValue = $configOptionQuantity;
      }
      $configOptions[$configOptionName] = $configOptionValue;
    }
    // dd($configOptions);

    $params["configoptions"] = $configOptions;
    $params["model"] = $serviceData;
    return $params;
  }

  protected function buildAddonParams(Hostingaddon $addonData)
  {
    $addonId = $addonData->id;
    $serviceId = $addonData->serviceId;
    $userId = $addonData->clientId;
    $domain = $addonData->service->domain;
    $username = $addonData->service->username;
    $password = $addonData->service->password;
    $pid = $addonData->addonId;
    $serverId = $addonData->serverId;
    $status = $addonData->status;
    $params = array();
    $params["accountid"] = $addonId;
    $params["addonId"] = $addonId;
    $params["serviceid"] = $serviceId;
    $params["userid"] = $userId;
    $params["domain"] = $domain;
    $params["username"] = $username;
    $params["password"] = \App\Helpers\Sanitize::decode((new \App\Helpers\Pwd)->decrypt($password));
    $params["packageid"] = $pid;
    $params["pid"] = $pid;
    $params["serverid"] = $serverId;
    $params["status"] = $status;
    $params["type"] = $addonData->productAddon->type;
    $params["producttype"] = $addonData->productAddon->type;
    $params["moduletype"] = $addonData->productAddon->module;
    if (!$params["moduletype"]) {
      return array();
    }
    $module = \Module::find($params["moduletype"]);
    if (!$module) {
      throw new \App\Exceptions\Module\NotServicable("Invalid Server Module Name");
    }
    foreach ($addonData->productAddon->moduleConfiguration as $moduleConfiguration) {
      $params[$moduleConfiguration->setting_name] = $moduleConfiguration->value;
      $params[$moduleConfiguration->friendly_name] = $moduleConfiguration->value;
    }
    $addonId = $addonData->id;
    $serviceId = $addonData->serviceId;
    $userId = $addonData->clientId;
    $domain = $addonData->service ? $addonData->service->domain : "";
    $username = $addonData->service ? $addonData->service->username : "";
    $password = $addonData->service ? $addonData->service->password : "";
    $pid = $addonData->addonId;
    $serverId = $addonData->serverId;
    $status = $addonData->status;

    $customFieldsTable = (new \App\Models\Customfield)->getTableName();
    $customFieldsValueTable = (new \App\Models\Customfieldsvalue)->getTableName();
    $customFields = DB::table("{$customFieldsTable}")->join("{$customFieldsValueTable}", "{$customFieldsValueTable}.fieldid", "=", "{$customFieldsTable}.id")->where("{$customFieldsValueTable}.relid", "=", $addonId)->where("{$customFieldsTable}.relid", "=", $pid)->where("{$customFieldsTable}.type", "=", "addon")->pluck("{$customFieldsValueTable}.value", "{$customFieldsTable}.fieldname")->toArray();
    foreach ($customFields as $fieldName => $fieldValue) {
      unset($customFields[$fieldName]);
      if (strpos($fieldName, "|")) {
        $parts = explode("|", $fieldName);
        $fieldName = trim($parts[0]);
      }
      if (strpos($fieldValue, "|")) {
        $parts = explode("|", $fieldValue);
        $fieldValue = trim($parts[0]);
      }
      $customFields[$fieldName] = $fieldValue;
    }
    if (array_key_exists("Username", $customFields)) {
      $params["username"] = $customFields["Username"];
      unset($customFields["Username"]);
    }
    if (array_key_exists("Password", $customFields)) {
      $params["password"] = $customFields["Password"];
      unset($customFields["Password"]);
    }
    if (array_key_exists("Domain", $customFields)) {
      $params["domain"] = $customFields["Domain"];
      unset($customFields["Domain"]);
    }
    $params["customfields"] = $customFields;
    $params["model"] = $addonData;
    return $params;
  }

  public static function generateRandomPassword()
  {
    return Str::random(20);
  }

  // Abstract module

  public function getType()
  {
    return $this->type;
  }

  public function callModule($function, array $params = array())
  {
    if ($this->functionExists($function)) {
      $params = array_merge($this->getParams(), $params);
      $moduleName = $this->getLoadedModule();
      $module = \Module::find($moduleName);
      if ($module) {
        $modName = $module->getName();
        $className = "\\Modules\\Servers\\{$modName}\\Http\\Controllers\\{$modName}Controller";
        $object = new $className();
        return $object->{$function}($params);
      } else {
        return "Module not found";
      }
    }
    return self::FUNCTIONDOESNTEXIST;
  }
  public function call($function, array $params = array())
  {
    $serviceID = (int) $this->serviceID;
    $addonId = (int) $this->addonId;
    $builtParams = array();
    if ($serviceID || $addonId) {
        $builtParams = $this->buildParams();
    }
    switch ($function) {
        case "CreateAccount":
            $action = "create";
            break;
        case "SuspendAccount":
            $action = "suspend";
            break;
        case "UnsuspendAccount":
            $action = "unsuspend";
            break;
        case "TerminateAccount":
            $action = "terminate";
            break;
        case "ChangePassword":
            $action = "changepw";
            break;
        case "ChangePackage":
            $action = "upgrade";
            break;
        default:
            $action = $function;
            break;
    }
    $params["action"] = $action;
    $builtParams = array_merge($builtParams, $params);
    return $this->callModule($function, $builtParams);
  }

  public function functionExists($name)
  {
    $moduleName = $this->getLoadedModule();
    $module = \Module::find($moduleName);
    if (!$moduleName || !$module) {
      return false;
    }
    $modName = $module->getName();
    $className = "\\Modules\\Servers\\{$modName}\\Http\\Controllers\\{$modName}Controller";
    $object = new $className();
    return method_exists($object, $name);
  }

  public function prepareParams($params)
  {
    $this->addParam("cbmsVersion", '1.0');
    if (version_compare($this->getAPIVersion(), "1.1", "<")) {
      $params = \App\Helpers\Sanitize::convertToCompatHtml($params);
    } else {
      if (version_compare($this->getAPIVersion(), "1.1", ">=")) {
        $params = \App\Helpers\Sanitize::decode($params);
      }
    }
    return $params;
  }

  public function getAPIVersion()
  {
    $APIVersion = $this->getMetaDataValue("APIVersion");
    if (!$APIVersion) {
      $APIVersion = $this->getDefaultAPIVersion();
    }
    return $APIVersion;
  }

  protected function getDefaultAPIVersion()
  {
    $moduleType = $this->getType();
    switch ($moduleType) {
        case "gateways":
            $version = "1.0";
            break;
        default:
            $version = "1.1";
    }
    return $version;
  }

  protected function addParam($key, $value)
  {
    $this->moduleParams[$key] = $value;
    return $this;
  }

  public function getParams()
  {
    $moduleParams = $this->moduleParams;
    return $this->prepareParams($moduleParams);
  }

  public function getModulePath($module)
  {
    $load = $module != null ? $module : "";
    return \Module::getModulePath($load);
  }

  protected function setLoadedModule($module)
  {
    $this->loadedmodule = $module;
  }

  public function getLoadedModule()
  {
    return $this->loadedmodule;
  }

  protected function setMetaData($metaData)
  {
    if (is_array($metaData)) {
      $this->metaData = $metaData;
      return true;
    }
    $this->metaData = array();
    return false;
  }

  protected function getMetaData()
  {
    $moduleName = $this->getLoadedModule();

    if ($this->functionExists("MetaData")) {
      return $this->call("MetaData");
    }
  }

  public function getMetaDataValue($keyName)
  {
    return array_key_exists($keyName, $this->metaData) ? $this->metaData[$keyName] : "";
  }

  public function load($module, $globalVariable = NULL)
  {
    $modpath = $this->getModulePath($module);
    // \Log::debug("Attempting to load module", array("type" => $this->getType(), "module" => $module, "path" => $modpath));
    // $moduleInstance = \Module::find($module);
    if (\Module::find($module)) {
    //   if ($moduleInstance->isEnabled()) {
        if (!is_null($globalVariable)) {
          global ${$globalVariable};
        }
        $this->setLoadedModule($module);
        $this->setMetaData($this->getMetaData());
        return true;
    //   }
      return false;
    }
    return false;
  }

  public function isApplicationLinkSupported()
  {
    return $this->functionExists("CreateApplicationLink") && $this->functionExists("DeleteApplicationLink");
  }

  public function isApplicationLinkingEnabled()
  {
    $appLink = \App\Models\AppLink::firstOrNew(array("module_type" => $this->getType(), "module_name" => $this->getLoadedModule()));
    return $appLink->isEnabled;
  }

  /**
   * getServerID
   */
  public static function getServerID($servertype, $servergroup)
  {
    $serverid = 0;
    $hostingCountsQuery = "(SELECT COUNT(id) FROM tblhosting WHERE tblhosting.server=tblservers.id AND domainstatus IN ('Active', 'Suspended'))";
    $hostingCountsQuery .= "+ (SELECT COUNT(id) FROM tblhostingaddons WHERE tblhostingaddons.server=tblservers.id AND status IN ('Active', 'Suspended'))";
    if ($servertype && !$servergroup) {
      $result = \App\Models\Server::selectRaw("id,maxaccounts,(" . $hostingCountsQuery . ") AS usagecount")
        ->where(array("type" => $servertype, "active" => "1", "disabled" => "0"));
    //   $data = $result->toArray();
      $data = $result;
      $serverid = $data->value("id") ?? 0;
      $maxaccounts = $data->value("maxaccounts") ?? 0;
      $usagecount = $data->value("usagecount") ?? 0;
      if ($serverid && $maxaccounts <= $usagecount) {
        $result = \App\Models\Server::selectRaw("id,((" . $hostingCountsQuery . ")/maxaccounts) AS percentusage")
        ->where('type', $servertype)
        ->where('id', '!=', $serverid)
        ->where('disabled', "0")
        ->orderBy("percentusage", 'ASC')
        ->first();

        $data = $result->toArray();
        if ($data) {
          $serverid = $data["id"];
          \App\Models\Server::where('type', $servertype)->update(['active', '']);
          \App\Models\Server::where('type', $servertype)->where('id', $serverid)->update(['active', 1]);
        }
      }
    } else {
      if ($servertype) {
        $result = \App\Models\Servergroup::where('id', $servergroup);
        $data = $result;
        $filltype = $data->value("filltype");
        $serverslist = array();
        $result = \App\Models\Servergroupsrel::where('groupid', $servergroup)->get();
        foreach ($result->toArray() as $data) {
          $serverslist[] = $data["serverid"];
        }
        if ($filltype == 1) {
          $result = \App\Models\Server::selectRaw("id,((" . $hostingCountsQuery . ")/maxaccounts) AS percentusage")
            ->whereIn('id', $serverslist)
            ->where('disabled', "0")
            ->orderBy("percentusage", 'ASC')
            ->first();
          $data = $result->toArray();
          $serverid = $data["id"];
        } else {
          if ($filltype == 2) {
            $result = \App\Models\Server::selectRaw("id,maxaccounts,(" . $hostingCountsQuery . ") AS usagecount")
              ->whereIn('id', $serverslist)
              ->where('active', "1")
              ->where('disabled', "0")
              ->first();
            $data = $result->toArray();
            $serverid = $data["id"];
            $maxaccounts = $data["maxaccounts"];
            $usagecount = $data["usagecount"];
            if ($serverid && $maxaccounts <= $usagecount) {
              $result = \App\Models\Server::selectRaw("id,((" . $hostingCountsQuery . ")/maxaccounts) AS percentusage")
                ->whereIn('id', $serverslist)
                ->where('disabled', "0")
                ->where('id', '!=', $serverid)
                ->orderBy("percentusage", 'ASC')
                ->first();
              $data = $result->toArray();
              if ($data) {
                $serverid = $data["id"];
                \App\Models\Server::where('type', $servertype)->update(['active', '']);
                \App\Models\Server::where('type', $servertype)->where('id', $serverid)->update(['active', 1]);
              }
            }
          }
        }
      }
    }
    return $serverid;
  }

  public function doSingleApplicationLinkCall($action)
  {
    if (!$this->isApplicationLinkSupported()) {
        throw new \Exception("Application linking not supported by module");
    }

    if (!$this->isApplicationLinkingEnabled()) {
        throw new \Exception("Application linking not enabled for module");
    }

    if (!in_array($action, array("Create", "Update", "Delete"))) {
        throw new \Exception("Invalid action requested");
    }

    $serviceId = $this->serviceID;
    if (!$serviceId) {
        throw new \Exception("Service ID is required");
    }

    $appLink = \App\Models\AppLink::firstOrCreate([
        "module_type" => $this->getType(),
        "module_name" => $this->getLoadedModule()
    ]);

    $params = $this->buildParams();
    $serverId = $params["serverid"];

    if ($this->functionExists("IsApplicationLinkingSupportedByServer")) {
        $isSupported = $this->call("IsApplicationLinkingSupportedByServer", $this->getServerParams($serverId));
    } else {
        $isSupported = true;
    }

    if (!$isSupported) {
        throw new \Exception("Application linking not supported by server this service is assigned to");
    }

    $appLinksToProvision = array();
    $permittedClientAreaScopes = array();
    if ($this->functionExists("GetSupportedApplicationLinks")) {
        $appLinksToProvision = $this->call("GetSupportedApplicationLinks");
        foreach ($appLink->links()->get() as $link) {
            if ($link->is_enabled) {
                $appLinksToProvision[$link->scope]["label"] = $link->display_label;
                $appLinksToProvision[$link->scope]["order"] = $link->order;
            } else {
                unset($appLinksToProvision[$link->scope]);
            }
        }

        $permittedClientAreaScopeNames = implode(" ", array_keys($appLinksToProvision));
    } else {
        $validScopes = \App\Models\OauthserverScope::where("scope", "LIKE", "clientarea:%")->pluck("scope")->all();
        $permittedClientAreaScopeNames = implode(" ", $validScopes);
    }

    if (strpos($permittedClientAreaScopeNames, "clientarea:sso") === false) {
        $permittedClientAreaScopeNames .= " clientarea:sso";
    }

    $clientCredentialCollection = array();
    if ($action == "Create") {
        // TODO
        // $server = \DI::make("oauth2_sso");
        // $storage = $server->getStorage("client_credentials");
        // $clientIdentifier = \WHMCS\ApplicationLink\Client::generateClientId();
        // $secret = \WHMCS\ApplicationLink\Client::generateSecret();
        // $storage->setClientDetails($clientIdentifier, $secret, "", "single_sign_on", $permittedClientAreaScopeNames, get_query_val("tblclients", "uuid", array("id" => $params["userid"])), $serviceId);
        // $clientCredentialCollection[] = \WHMCS\ApplicationLink\Client::where("identifier", "=", $clientIdentifier)->first();
    } else if ($action == "Update") {
        $clientCredential = \App\Models\OauthserverClient::where("service_id", $serviceId)->first();
        if (is_null($clientCredential)) {
            throw new \Exception("Existing application link credential not found");
        }

        $clientCredential->secret = base64_encode(\phpseclib3\Crypt\Random::string(64));
        $clientCredential->save();
        $clientCredentialCollection[] = $clientCredential;
    } else if ($action == "Delete") {
        $clientCredential = \App\Models\OauthserverClient::where("service_id", $serviceId)->first();
        if (is_null($clientCredential)) {
            throw new \Exception("Existing application link credential not found");
        }

        $clientCredentialCollection[] = $clientCredential;
        $clientCredential->delete();
    }

    $systemUrl = config('app.url_admin');
    $params = $this->getServerParams($serverId) + array(
        "systemUrl" => $systemUrl,
        "tokenEndpoint" => $systemUrl . "oauth/token.php",
        "clientCredentialCollection" => $clientCredentialCollection,
        "appLinks" => $appLinksToProvision
    );

    if (!$this->functionExists($action . "ApplicationLink")) {
        throw new \Exception("Module does not supported requested Application Link Action: \"" . $action . "\"");
    }

    $errors = $this->call($action . "ApplicationLink", $params);
    if (is_array($errors) && 0 < count($errors)) {
        return $errors;
    }

  }

    public function getSingleSignOnUrlForService()
    {
        $serverId = $this->modelData->serverId;
        return $this->getSingleSignOnURL($serverId, false);
    }

    protected function getSingleSignOnUrl($serverId, $admin)
    {
        $functionToCall = $admin ? "AdminSingleSignOn" : "ServiceSingleSignOn";
        $serverModel = \App\Models\Server::find($serverId);

        if (!$serverModel) {
            throw new \App\Exceptions\Module\SingleSignOnError("Server ID not found.");
        }

        if ($this->load($serverModel->type)) {
            if (!$this->functionExists($functionToCall)) {
                throw new \App\Exceptions\Module\SingleSignOnError("Invalid Server ID for Auto Login.");
            }

            $params = $this->getServerParams($serverModel);
            $results = $this->call($functionToCall, $params);
            if (is_array($results) && isset($results["success"]) && $results["success"] == true) {
                return $results["redirectTo"];
            }

            if (is_array($results) && isset($results["errorMsg"])) {
                throw new \App\Exceptions\Module\SingleSignOnError($results["errorMsg"]);
            }

            throw new \App\Exceptions\Module\SingleSignOnError("Unable to auto-login.");
        }

        throw new \App\Exceptions\Module\SingleSignOnError("Invalid Server Module.");
    }

    public function getServerListForModule()
    {
        $servers = array();
        $disabledServers = array();
        $serverCollection = \App\Models\Server::where("type", "=", $this->addonModule ?: $this->serviceModule)->orderBy("name")->get();

        if ($serverCollection) {
            $hostingCounts = \App\Models\Hosting::selectRaw("domainstatus, count(id) as totalService, server")->whereIn("domainstatus", array("Active", "Suspended"))->groupBy("server")->pluck("server", "totalService");
            $hostingAddonsCounts = \App\Models\Hostingaddon::selectRaw("status, count(id) as totalAddon, server")->whereIn("status", array("Active", "Suspended"))->groupBy("server")->pluck("server", "totalAddon");

            foreach ($serverCollection as $server) {
                $serverId = $server->id;
                $serverName = $server->name;
                $serverMaxAccounts = $server->maxaccounts;
                $disabled = $server->disabled;
                if ($disabled) {
                    $serverName .= " (" . __("admin.emailtplsdisabled") . ")";
                }

                $serverNumberAccounts = ($hostingCounts[$serverId] ?? 0) + ($hostingAddonsCounts[$serverId] ?? 0);
                $label = $serverName . " (" . $serverNumberAccounts . "/" . $serverMaxAccounts . " " . __("admin.fieldsaccounts") . ")";
                if ($disabled) {
                    $disabledServers[$serverId] = $label;
                } else {
                    $servers[$serverId] = $label;
                }
            }
        }

        return array_replace($servers, $disabledServers);
    }
  public function getListWithDisplayNames()
  {
    $serverList = array();
    foreach ($this->getList() as $module) {
      $moduleName = $module->getLowerName();
      $this->load($moduleName);
      if ($this->isMetaDataValueSet("NoEditModuleSettings") && $this->getMetaDataValue("NoEditModuleSettings")) {
        continue;
      }
      $serverList[$moduleName] = $this->getDisplayName();
    }
    return $serverList;
  }
  public function getDisplayName()
  {
    $DisplayName = $this->getMetaDataValue("DisplayName");
    if (!$DisplayName) {
      $DisplayName = ucfirst($this->getLoadedModule());
    }
    return \App\Helpers\Sanitize::makeSafeForOutput($DisplayName);
  }
  public function isMetaDataValueSet($keyName)
  {
    return array_key_exists($keyName, $this->metaData);
  }
  public function getList()
  {
    $data = [];
    $modules = \Module::toCollection();
    foreach ($modules as $key => $module) {
      if (strpos($module->getPath(), '/Servers') !== false) {
        $data[] = $module;
      }
    }
    return $data;
  }
  public function findTemplate($templateName)
  {
    // $currentTheme = \Route::currentRouteName();
    // $html = view($templateName)->render();
    $module = \Module::find($this->getLoadedModule());
    if ($module) {
      if (strpos($templateName, ":") !== false) {
        return $templateName;
      } else {
        return $module->getLowerName()."::".$templateName;
      }
    }
    return "";
  }
}
