@php

    echo "<div>\n\n<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"50%\" valign=\"top\">\n\n";
    if (count($customfields)) {
        echo "<b>Custom Defined Merge Fields</b><br /><table>";
        foreach ($customfields as $fields) {
            foreach ($fields as $k => $v) {
                echo "<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('" . $k . "');return false\">" . $v . "</a></td><td>{{\$" . $k . "}}</td></tr>";
            }
        }
        echo "</table><br />";
    }

    if ($type == "support") {
        echo "<b>";
        echo  __("admin.mergefieldssupport");
        echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('ticket_id');return false\">";
        echo  __("admin.fieldsid");
        echo "</a></td><td>{{\$ticket_id}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_department');return false\">";
        echo  __("admin.supportdepartment");
        echo "</a></td><td>{{\$ticket_department}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_date_opened');return false\">";
        echo  __("admin.mergefieldsdateopened");
        echo "</a></td><td>{{\$ticket_date_opened}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_subject');return false\">";
        echo  __("admin.fieldssubject");
        echo "</a></td><td>{{\$ticket_subject}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_message');return false\">";
        echo  __("admin.mergefieldsmessage");
        echo "</a></td><td>{{\$ticket_message}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_status');return false\">";
        echo  __("admin.fieldsstatus");
        echo "</a></td><td>{{\$ticket_status}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_priority');return false\">";
        echo  __("admin.supportpriority");
        echo "</a></td><td>{{\$ticket_priority}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_url');return false\">";
        echo  __("admin.mergefieldsticketurl");
        echo "</a></td><td>{{\$ticket_url}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_link');return false\">";
        echo  __("admin.mergefieldsticketlink");
        echo "</a></td><td>{{\$ticket_link}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_auto_close_time');return false\">";
        echo  __("admin.mergefieldsautoclosetime");
        echo "</a></td><td>{{\$ticket_auto_close_time}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_kb_auto_suggestions');return false\">";
        echo  __("admin.mergefieldskbautosuggestions");
        echo "</a></td><td>{{\$ticket_kb_auto_suggestions}}</td></tr>\n</table><br />\n";
    } else {
        if ($type == "affiliate") {
            echo "<b>";
            echo  __("admin.mergefieldsaffiliate");
            echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('affiliate_total_visits');return false\">";
            echo  __("admin.mergefieldsnoreferrals");
            echo "</a></td><td>{{\$affiliate_total_visits}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('affiliate_balance');return false\">";
            echo  __("admin.mergefieldsearnbalance");
            echo "</a></td><td>{{\$affiliate_balance}}</td></tr>\n<tr><td nowrap><a href=\"#\" onclick=\"insertMergeField('affiliate_withdrawn');return false\">";
            echo  __("admin.mergefieldswithdrawnamount");
            echo "</a></td><td>{{\$affiliate_withdrawn}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('affiliate_referrals_table');return false\">";
            echo  __("admin.mergefieldsrefdetails");
            echo "</a></td><td>{{\$affiliate_referrals_table}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('affiliate_referral_url');return false\">";
            echo  __("admin.mergefieldsrefurl");
            echo "</a></td><td>{{\$affiliate_referral_url}}</td></tr>\n</table><br />\n";
        } else {
            if ($type == "addon") {
                echo "<b>";
                echo  __("admin.mergefieldsaddon");
                echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('addon_reg_date');return false\">";
                echo  __("admin.fieldssignupdate");
                echo "</a></td><td>{{\$addon_reg_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_product');return false\">";
                echo  __("admin.mergefieldsparentproduct");
                echo "</a></td><td>{{\$addon_product}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_domain');return false\">";
                echo  __("admin.mergefieldsparentdomain");
                echo "</a></td><td>{{\$addon_domain}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_name');return false\">";
                echo  __("admin.fieldsname");
                echo "</a></td><td>{{\$addon_name}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_setup_fee');return false\">";
                echo  __("admin.fieldssetupfee");
                echo "</a></td><td>{{\$addon_setup_fee}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_recurring_amount');return false\">";
                echo  __("admin.fieldsrecurringamount");
                echo "</a></td><td>{{\$addon_recurring_amount}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_billing_cycle');return false\">";
                echo  __("admin.fieldsbillingcycle");
                echo "</a></td><td>{{\$addon_billing_cycle}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_payment_method');return false\">";
                echo  __("admin.fieldspaymentmethod");
                echo "</a></td><td>{{\$addon_payment_method}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_next_due_date');return false\">";
                echo  __("admin.fieldsnextduedate");
                echo "</a></td><td>{{\$addon_next_due_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_status');return false\">";
                echo  __("admin.fieldsstatus");
                echo "</a></td><td>{{\$addon_status}}</td></tr>\n</table><br />\n";
            } else {
                if ($type == "domain") {
                    echo "<b>";
                    echo  __("admin.mergefieldsdomain");
                    echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('domain_order_id');return false\">";
                    echo  __("admin.fieldsorderid");
                    echo "</a></td><td>{{\$domain_order_id}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_reg_date');return false\">";
                    echo  __("admin.fieldssignupdate");
                    echo "</a></td><td>{{\$domain_reg_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_name');return false\">";
                    echo  __("admin.fieldsdomain");
                    echo "</a></td><td>{{\$domain_name}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_sld');return false\">";
                    echo  __("admin.mergefieldssld");
                    echo "</a></td><td>{{\$domain_sld}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_tld');return false\">";
                    echo  __("admin.mergefieldstld");
                    echo "</a></td><td>{{\$domain_tld}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_reg_period');return false\">";
                    echo  __("admin.fieldsregperiod");
                    echo "</a></td><td>{{\$domain_reg_period}}</td></tr>\n<tr><td nowrap><a href=\"#\" onclick=\"insertMergeField('domain_first_payment_amount');return false\">";
                    echo  __("admin.fieldsfirstpaymentamount");
                    echo "</a></td><td>{{\$domain_first_payment_amount}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_recurring_amount');return false\">";
                    echo  __("admin.fieldsrecurringamount");
                    echo "</a></td><td>{{\$domain_recurring_amount}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_next_due_date');return false\">";
                    echo  __("admin.fieldsnextduedate");
                    echo "</a></td><td>{{\$domain_next_due_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_subscription_id');return false\">";
                    echo  __("admin.mergefieldsdomainSubscriptionId");
                    echo "</td><td>{{\$domain_subscription_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_expiry_date');return false\">";
                    echo  __("admin.fieldsexpirydate");
                    echo "</a></td><td>{{\$domain_expiry_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_registrar');return false\">";
                    echo  __("admin.fieldsregistrar");
                    echo "</a></td><td>{{\$domain_registrar}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_renewal_url');return false\">";
                    echo  __("admin.fieldsrenewalLink");
                    echo "</a></td><td>{{\$domain_renewal_url}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domains_manage_url');return false\">";
                    echo  __("admin.fieldsdomainsList");
                    echo "</a></td><td>{{\$domains_manage_url}}</td></tr>\n<tr>\n    <td colspan=\"2\">\n        <strong>";
                    echo  __("admin.mergefieldsdaysUntilInformation");
                    echo "</strong><br />\n        ";
                    echo  __("admin.mergefieldsdaysUntilInformation2");
                    echo "    </td>\n</tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_days_until_expiry');return false\">";
                    echo  __("admin.mergefieldsdaysexpiry");
                    echo "</a></td><td>{{\$domain_days_until_expiry}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_days_until_nextdue');return false\">";
                    echo  __("admin.mergefieldsdaysnextdue");
                    echo "</a></td><td>{{\$domain_days_until_nextdue}}</td></tr>\n<tr>\n    <td colspan=\"2\">\n        <strong>";
                    echo  __("admin.mergefieldsdaysAfterInformation");
                    echo "</strong>\n    </td>\n</tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_days_after_expiry');return false\">";
                    echo  __("admin.mergefieldsdaysAfterExpiry");
                    echo "</a></td><td>{{\$domain_days_after_expiry}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_days_after_nextdue');return false\">";
                    echo  __("admin.mergefieldsdaysAfterNextDue");
                    echo "</a></td><td>{{\$domain_days_after_nextdue}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_status');return false\">";
                    echo  __("admin.fieldsstatus");
                    echo "</a></td><td>{{\$domain_status}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_dns_management');return false\">";
                    echo  __("admin.domainsdnsmanagement");
                    echo "</a></td><td>{{\$domain_dns_management}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_email_forwarding');return false\">";
                    echo  __("admin.domainsemailforwarding");
                    echo "</a></td><td>{{\$domain_email_forwarding}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_id_protection');return false\">";
                    echo  __("admin.domainsidprotection");
                    echo "</a></td><td>{{\$domain_id_protection}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_do_not_renew');return false\">";
                    echo  __("admin.mergefieldsdonotrenew");
                    echo "</a></td><td>{{\$domain_do_not_renew}}</td></tr>\n</table><br />\n";
                } else {
                    if ($type == "invoice") {
                        echo "<b>";
                        echo  __("admin.mergefieldsinvoice");
                        echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('invoice_id');return false\">";
                        echo  __("admin.fieldsinvoiceid");
                        echo "</a></td><td>{{\$invoice_id}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_num');return false\">";
                        echo  __("admin.fieldsinvoicenum");
                        echo "</a></td><td>{{\$invoice_num}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_date_created');return false\">";
                        echo  __("admin.mergefieldsdatecreated");
                        echo "</a></td><td>{{\$invoice_date_created}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_date_due');return false\">";
                        echo  __("admin.fieldsduedate");
                        echo "</a></td><td>{{\$invoice_date_due}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_date_paid');return false\">";
                        echo  __("admin.fieldsdatepaid");
                        echo "</a></td><td>{{\$invoice_date_paid}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_items');return false\">";
                        echo  __("admin.mergefieldsinvoiceitems");
                        echo "</a></td><td>{{\$invoice_items}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_html_contents');return false\">";
                        echo  __("admin.mergefieldsinvoiceitemshtml");
                        echo "</a></td><td>{{\$invoice_html_contents}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_subtotal');return false\">";
                        echo  __("admin.fieldssubtotal");
                        echo "</a></td><td>{{\$invoice_subtotal}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_tax');return false\">";
                        echo  __("admin.fieldstax");
                        echo "</a></td><td>{{\$invoice_tax}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_tax_rate');return false\">";
                        echo  __("admin.fieldstaxrate");
                        echo "</a></td><td>{{\$invoice_tax_rate}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_credit');return false\">";
                        echo  __("admin.fieldscredit");
                        echo "</a></td><td>{{\$invoice_credit}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_total');return false\">";
                        echo  __("admin.fieldstotal");
                        echo "</a></td><td>{{\$invoice_total}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_amount_paid');return false\">";
                        echo  __("admin.mergefieldsamountpaid");
                        echo "</a></td><td>{{\$invoice_amount_paid}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_balance');return false\">";
                        echo  __("admin.fieldsbalance");
                        echo "</a></td><td>{{\$invoice_balance}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_last_payment_amount');return false\">";
                        echo  __("admin.mergefieldslastpaymentamount");
                        echo "</a></td><td>{{\$invoice_last_payment_amount}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_last_payment_transid');return false\">";
                        echo  __("admin.mergefieldslastpaymenttransid");
                        echo "</a></td><td>{{\$invoice_last_payment_transid}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_payment_method');return false\">";
                        echo  __("admin.fieldspaymentmethod");
                        echo "</a></td><td>{{\$invoice_payment_method}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_pay_method_type');return false\">";
                        echo  __("admin.fieldspayMethodType");
                        echo "</a></td><td>{{\$invoice_pay_method_type}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_pay_method_description');return false\">";
                        echo  __("admin.fieldspayMethodDescription");
                        echo "</a></td><td>{{\$invoice_pay_method_description}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_pay_method_display_name');return false\">";
                        echo  __("admin.fieldspayMethodDisplayName");
                        echo "</a></td><td>{{\$invoice_pay_method_display_name}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_pay_method_expiry');return false\">";
                        echo  __("admin.fieldsexpdate");
                        echo "</a></td><td>{{\$invoice_pay_method_expiry}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_auto_capture_available');return false\">";
                        echo  __("admin.fieldspayMethod");
                        echo "</a></td><td>{{\$invoice_auto_capture_available}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_payment_link');return false\">";
                        echo  __("admin.mergefieldspaymentlink");
                        echo "</a></td><td>{{\$invoice_payment_link}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_next_payment_attempt_date');return false\">";
                        echo  __("admin.mergefieldsnextPaymentAttempt");
                        echo "</a></td><td>{{\$invoice_next_payment_attempt_date}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_subscription_id');return false\">";
                        echo  __("admin.fieldssubscriptionid");
                        echo "</a></td><td>{{\$invoice_subscription_id}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_status');return false\">";
                        echo  __("admin.fieldsstatus");
                        echo "</a></td><td>{{\$invoice_status}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_link');return false\">";
                        echo  __("admin.mergefieldsinvoicelink");
                        echo "</a></td><td>{{\$invoice_link}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_previous_balance');return false\">";
                        echo  __("admin.mergefieldsprevbalance");
                        echo "</a></td><td>{{\$invoice_previous_balance}}</td></tr>\n<tr><td nowrap><a href=\"#\" onclick=\"insertMergeField('invoice_total_balance_due');return false\">";
                        echo  __("admin.mergefieldsinvoicesbalance");
                        echo "</a></td><td>{{\$invoice_total_balance_due}}</td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_notes');return false\">";
                        echo  __("admin.fieldsnotes");
                        echo "</a></td><td>{{\$invoice_notes}}</td></tr>\n</table><br />\n";
                    } else {
                        if ($type == "product") {
                            echo "<b>";
                            echo  __("admin.mergefieldsproduct");
                            echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('service_order_id');return false\">";
                            echo  __("admin.fieldsorderid");
                            echo "</td><td>{{\$service_order_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_id');return false\">";
                            echo  __("admin.fieldsid");
                            echo "</td><td>{{\$service_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_reg_date');return false\">";
                            echo  __("admin.fieldssignupdate");
                            echo "</td><td>{{\$service_reg_date}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_product_name');return false\">";
                            echo  __("admin.mergefieldsprodname");
                            echo "</td><td>{{\$service_product_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_product_description');return false\">";
                            echo  __("admin.mergefieldsproddesc");
                            echo "</td><td>{{\$service_product_description}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_domain');return false\">";
                            echo  __("admin.fieldsdomain");
                            echo "</td><td>{{\$service_domain}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_config_options');return false\">";
                            echo  __("admin.mergefieldsconfigoptions");
                            echo "</td><td>{{\$service_config_options}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_server_name');return false\">";
                            echo  __("admin.mergefieldsservername");
                            echo "</td><td>{{\$service_server_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_server_hostname');return false\">";
                            echo  __("admin.mergefieldsserverhostname");
                            echo "</td><td>{{\$service_server_hostname}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_server_ip');return false\">";
                            echo  __("admin.mergefieldsserverip");
                            echo "</td><td>{{\$service_server_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_dedicated_ip');return false\">";
                            echo  __("admin.mergefieldsdedicatedip");
                            echo "</td><td>{{\$service_dedicated_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_assigned_ips');return false\">";
                            echo  __("admin.mergefieldsassignedips");
                            echo "</td><td>{{\$service_assigned_ips}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns1');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 1</td><td>{{\$service_ns1}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns2');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 2</td><td>{{\$service_ns2}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns3');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 3</td><td>{{\$service_ns3}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns4');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 4</td><td>{{\$service_ns4}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns5');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 5</td><td>{{\$service_ns5}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns1_ip');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 1 ";
                            echo  __("admin.mergefieldsip");
                            echo "</td><td>{{\$service_ns1_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns2_ip');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 2 ";
                            echo  __("admin.mergefieldsip");
                            echo "</td><td>{{\$service_ns2_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns3_ip');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 3 ";
                            echo  __("admin.mergefieldsip");
                            echo "</td><td>{{\$service_ns3_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns4_ip');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 4 ";
                            echo  __("admin.mergefieldsip");
                            echo "</td><td>{{\$service_ns4_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_ns5_ip');return false\">";
                            echo  __("admin.mergefieldsnameserver");
                            echo " 5 ";
                            echo  __("admin.mergefieldsip");
                            echo "</td><td>{{\$service_ns5_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_payment_method');return false\">";
                            echo  __("admin.fieldspaymentmethod");
                            echo "</td><td>{{\$service_payment_method}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_first_payment_amount');return false\">";
                            echo  __("admin.fieldsfirstpaymentamount");
                            echo "</td><td>{{\$service_first_payment_amount}}</a></td></tr>\n<tr><td nowrap><a href=\"#\" onclick=\"insertMergeField('service_recurring_amount');return false\">";
                            echo  __("admin.mergefieldsrecurringpayment");
                            echo "</td><td>{{\$service_recurring_amount}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_billing_cycle');return false\">";
                            echo  __("admin.fieldsbillingcycle");
                            echo "</td><td>{{\$service_billing_cycle}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_next_due_date');return false\">";
                            echo  __("admin.fieldsnextduedate");
                            echo "</td><td>{{\$service_next_due_date}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_subscription_id');return false\">";
                            echo  __("admin.mergefieldsserviceSubscriptionId");
                            echo "</td><td>{{\$service_subscription_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('addon_subscription_id');return false\">";
                            echo  __("admin.mergefieldsaddonSubscriptionId");
                            echo "</td><td>{{\$addon_subscription_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_status');return false\">";
                            echo  __("admin.fieldsstatus");
                            echo "</td><td>{{\$service_status}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_suspension_reason');return false\">";
                            echo  __("admin.mergefieldssuspreason");
                            echo "</td><td>{{\$service_suspension_reason}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_cancellation_type');return false\">";
                            echo  __("admin.mergefieldscanceltype");
                            echo "</td><td>{{\$service_cancellation_type}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_username');return false\">";
                            echo  __("admin.fieldsusername");
                            echo "</td><td>{{\$service_username}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_password');return false\">";
                            echo  __("admin.fieldspassword");
                            echo "</td><td>{{\$service_password}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_custom_fields');return false\">";
                            echo  __("admin.mergefieldscustomfieldsarray");
                            echo "</td><td>{{\$service_custom_fields.1}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_custom_fields_by_name');return false\">";
                            echo  __("admin.mergefieldscustomfieldsarray");
                            echo "</td><td>{{\$service_custom_fields_by_name.0.name}}: 
                                    {{\$service_custom_fields_by_name.0.value}}}</a></td></tr>\n</table><br />\n";
                        } else {
                            if ($type == "notification") {
                                echo "<b>";
                                echo  __("admin.mergefieldsnotification");
                                echo "</b><br />\n<table>\n    <tr>\n        <td width=\"150\">\n            <a href=\"#\" onclick=\"insertMergeField('notification_title');return false\">";
                                echo  __("admin.mergefieldsnotificationTitle");
                                echo "</a>\n        </td>\n        <td>\n            {{\$notification_title}}\n        </td>\n    </tr>\n    <tr>\n        <td>\n            <a href=\"#\" onclick=\"insertMergeField('notification_url');return false\">";
                                echo  __("admin.mergefieldsnotificationUrl");
                                echo "</a>\n        </td>\n        <td>\n            {{\$notification_url}}\n        </td>\n    </tr>\n    <tr>\n        <td>\n            <a href=\"#\" onclick=\"insertMergeField('notification_message');return false\">";
                                echo  __("admin.mergefieldsnotificationMessage");
                                echo "</a>\n        </td>\n        <td>\n            {{\$notification_message}}\n        </td>\n    </tr>\n    <tr>\n        <td>\n            <a href=\"#\" onclick=\"insertMergeField('notification_attributes');return false\">";
                                echo  __("admin.mergefieldsnotificationAttributes");
                                echo "</a>\n        </td>\n        <td>\n            {{\$notification_attributes}}\n
                                            </td>\n    </tr>\n    <tr>\n        <td colspan=\"2\">\n            {foreach \$notification_attributes as \$attribute}<br />\n                &nbsp;&nbsp;&nbsp;&nbsp;{{\$attribute.label}} {*";
                                echo  __("admin.mergefieldsnotificationAttributesLabel");
                                echo "*}<br />\n                &nbsp;&nbsp;&nbsp;&nbsp;{{\$attribute.value}} {*";
                                echo  __("admin.mergefieldsnotificationAttributesValue");
                                echo "*}<br />\n                &nbsp;&nbsp;&nbsp;&nbsp;{{\$attribute.url}} {*";
                                echo  __("admin.mergefieldsnotificationAttributesUrl");
                                echo "*}<br />\n                &nbsp;&nbsp;&nbsp;&nbsp;{{\$attribute.style}} {*";
                                echo  __("admin.mergefieldsnotificationAttributesStyle");
                                echo "*}<br />\n                &nbsp;&nbsp;&nbsp;&nbsp;{{\$attribute.icon}} {*";
                                echo  __("admin.mergefieldsnotificationAttributesIcon");
                                echo "*}<br />\n            {/foreach}\n        </td>\n    </tr>\n</table><br />\n";
                            } else {
                                if ($type == "admin") {
                                    if (isset($name) && $name == "New Order Notification") {
                                        echo "<b>";
                                        echo  __("admin.mergefieldsorder");
                                        echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
                                        echo  __("admin.fieldsorderid");
                                        echo "</td><td>{{\$order_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_number');return false\">";
                                        echo  __("admin.fieldsordernum");
                                        echo "</td><td>{{\$order_number}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_date');return false\">";
                                        echo  __("admin.mergefieldsorderdate");
                                        echo "</td><td>{{\$order_date}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_items');return false\">";
                                        echo  __("admin.ordersitems");
                                        echo "</td><td>{{\$order_items}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_total');return false\">";
                                        echo  __("admin.mergefieldsduetoday");
                                        echo "</td><td>{{\$order_total}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_payment_method');return false\">";
                                        echo  __("admin.fieldspaymentmethod");
                                        echo "</td><td>{{\$order_payment_method}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('invoice_id');return false\">";
                                        echo  __("admin.fieldsinvoiceid");
                                        echo "</td><td>{{\$invoice_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('order_notes');return false\">";
                                        echo  __("admin.mergefieldsordernotes");
                                        echo "</td><td>{{\$order_notes}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_ip');return false\">";
                                        echo  __("admin.mergefieldsclientip");
                                        echo "</td><td>{{\$client_ip}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_hostname');return false\">";
                                        echo  __("admin.mergefieldsclienthostname");
                                        echo "</td><td>{{\$client_hostname}}</a></td></tr>\n</table><br />\n<b>";
                                        echo  __("admin.mergefieldsclient");
                                        echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
                                        echo  __("admin.fieldsid");
                                        echo "</td><td>{{\$client_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_first_name');return false\">";
                                        echo  __("admin.fieldsfirstname");
                                        echo "</td><td>{{\$client_first_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_last_name');return false\">";
                                        echo  __("admin.fieldslastname");
                                        echo "</td><td>{{\$client_last_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_company_name');return false\">";
                                        echo  __("admin.fieldscompanyname");
                                        echo "</td><td>{{\$client_company_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_email');return false\">";
                                        echo  __("admin.fieldsemail");
                                        echo "</td><td>{{\$client_email}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_address1');return false\">";
                                        echo  __("admin.fieldsaddress1");
                                        echo "</td><td>{{\$client_address1}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_address2');return false\">";
                                        echo  __("admin.fieldsaddress2");
                                        echo "</td><td>{{\$client_address2}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_city');return false\">";
                                        echo  __("admin.fieldscity");
                                        echo "</td><td>{{\$client_city}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_state');return false\">";
                                        echo  __("admin.fieldsstate");
                                        echo "</td><td>{{\$client_state}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_postcode');return false\">";
                                        echo  __("admin.fieldspostcode");
                                        echo "</td><td>{{\$client_postcode}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_country');return false\">";
                                        echo  __("admin.fieldscountry");
                                        echo "</td><td>{{\$client_country}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_phonenumber');return false\">";
                                        echo  __("admin.fieldsphonenumber");
                                        echo "</td><td>{{\$client_phonenumber}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_customfields');return false\">";
                                        echo  __("admin.customfieldsclienttitle");
                                        echo "</td><td>{{\$client_customfields}}</a></td></tr>\n</table><br />\n";
                                    } else {
                                        if (isset($name) && ($name == "Automatic Setup Successful" || $name == "Automatic Setup Failed" || $name == "Service Unsuspension Failed" || $name == "Service Unsuspension Successful")) {
                                            echo "<b>";
                                            echo  __("admin.mergefieldsservice");
                                            echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
                                            echo  __("admin.fieldsclientid");
                                            echo "</td><td>{{\$client_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_id');return false\">";
                                            echo  __("admin.mergefieldsserviceid");
                                            echo "</td><td>{{\$service_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_product');return false\">";
                                            echo  __("admin.fieldsproduct");
                                            echo "</td><td>{{\$service_product}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('service_domain');return false\">";
                                            echo  __("admin.fieldsdomain");
                                            echo "</td><td>{{\$service_domain}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('error_msg');return false\">";
                                            echo  __("admin.mergefieldserrormsg");
                                            echo "</td><td>{{\$error_msg}}</a></td></tr>\n</table><br />\n<b>";
                                            echo  __("admin.mergefieldsdomain");
                                            echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
                                            echo  __("admin.fieldsclientid");
                                            echo "</td><td>{{\$client_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_id');return false\">";
                                            echo  __("admin.mergefieldsdomainid");
                                            echo "</td><td>{{\$domain_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_type');return false\">";
                                            echo  __("admin.domainsregtype");
                                            echo "</td><td>{{\$domain_type}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('domain_name');return false\">";
                                            echo  __("admin.mergefieldsdomainname");
                                            echo "</td><td>{{\$domain_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('error_msg');return false\">";
                                            echo  __("admin.mergefieldserrormsg");
                                            echo "</td><td>{{\$error_msg}}</a></td></tr>\n</table><br />\n";
                                        } else {
                                            if (isset($name) && $name == "Support Ticket Change Notification") {
                                                echo "<b>";
                                                echo  __("admin.mergefieldssupport");
                                                echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('ticket_id');return false\">";
                                                echo  __("admin.fieldsid");
                                                echo "</td><td>{{\$ticket_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_tid');return false\">";
                                                echo  __("admin.supportticketid");
                                                echo "</td><td>{{\$ticket_tid}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
                                                echo  __("admin.fieldsclientid");
                                                echo "</td><td>{{\$client_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_name');return false\">";
                                                echo  __("admin.fieldsclientname");
                                                echo "</td><td>{{\$client_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_department');return false\">";
                                                echo  __("admin.supportdepartment");
                                                echo "</td><td>{{\$ticket_department}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_subject');return false\">";
                                                echo  __("admin.fieldssubject");
                                                echo "</td><td>{{\$ticket_subject}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('ticket_priority');return false\">";
                                                echo  __("admin.supportpriority");
                                                echo "</td><td>{{\$ticket_priority}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('changer');return false\">";
                                                echo  __("admin.mergefieldschanger");
                                                echo "</td><td>{{\$changer}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('changes');return false\">";
                                                echo  __("admin.mergefieldsticketChanges");
                                                echo "</td><td>{{\$changes}} (array)</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('newTicket');return false\">";
                                                echo  __("admin.mergefieldsnewTicket");
                                                echo "</td><td>{{\$newTicket}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('newReply');return false\">";
                                                echo  __("admin.mergefieldsnewReply");
                                                echo "</td><td>{{\$newReply}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('newNote');return false\">";
                                                echo  __("admin.mergefieldsnewNote");
                                                echo "</td><td>{{\$newNote}}</a></td></tr>\n</table><br />\n";
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    if (!in_array($type, array("support", "admin", "notification"))) {
        echo "<b>";
        echo  __("admin.mergefieldsclient");
        echo "</b><br />\n<table>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('client_id');return false\">";
        echo  __("admin.fieldsid");
        echo "</td><td>{{\$client_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_name');return false\">";
        echo  __("admin.fieldsclientname");
        echo "</td><td>{{\$client_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_first_name');return false\">";
        echo  __("admin.fieldsfirstname");
        echo "</td><td>{{\$client_first_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_last_name');return false\">";
        echo  __("admin.fieldslastname");
        echo "</td><td>{{\$client_last_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_company_name');return false\">";
        echo  __("admin.fieldscompanyname");
        echo "</td><td>{{\$client_company_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_email');return false\">";
        echo  __("admin.fieldsemail");
        echo "</td><td>{{\$client_email}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_address1');return false\">";
        echo  __("admin.fieldsaddress1");
        echo "</td><td>{{\$client_address1}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_address2');return false\">";
        echo  __("admin.fieldsaddress2");
        echo "</td><td>{{\$client_address2}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_city');return false\">";
        echo  __("admin.fieldscity");
        echo "</td><td>{{\$client_city}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_state');return false\">";
        echo  __("admin.fieldsstate");
        echo "</td><td>{{\$client_state}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_postcode');return false\">";
        echo  __("admin.fieldspostcode");
        echo "</td><td>{{\$client_postcode}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_country');return false\">";
        echo  __("admin.fieldscountry");
        echo "</td><td>{{\$client_country}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_phonenumber');return false\">";
        echo  __("admin.fieldsphonenumber");
        echo "</td><td>{{\$client_phonenumber}}</a></td></tr>\n<tr>\n    <td>\n        <a href=\"#\" onclick=\"insertMergeField('client_tax_id');return false\">\n            ";
        echo __("admin." .\App\Helpers\Vat::getLabel("fields"));
        echo "        </a>\n    </td>\n    <td>{{\$client_tax_id}}</td>\n</tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_password');return false\">";
        echo  __("admin.fieldspassword");
        echo "</td><td>{{\$client_password}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_signup_date');return false\">";
        echo  __("admin.fieldssignupdate");
        echo " </td><td>{{\$client_signup_date}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_credit');return false\">";
        echo  __("admin.clientscreditbalance");
        echo "</td><td>{{\$client_credit}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_cc_description');return false\">";
        echo  __("admin.fieldspayMethodDescription");
        echo "</td><td>{{\$client_cc_description}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_cc_type');return false\">";
        echo  __("admin.fieldscardtype");
        echo "</td><td>{{\$client_cc_type}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_cc_number');return false\">";
        echo  __("admin.fieldscardlast4");
        echo "</td><td>{{\$client_cc_number}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_cc_expiry');return false\">";
        echo  __("admin.fieldsexpdate");
        echo "</td><td>{{\$client_cc_expiry}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_gateway_id');return false\">";
        echo  __("admin.fieldsgatewayid");
        echo "</td><td>{{\$client_gateway_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_group_id');return false\">";
        echo  __("admin.mergefieldsclientgroupid");
        echo "</td><td>{{\$client_group_id}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_group_name');return false\">";
        echo  __("admin.mergefieldsclientgroupname");
        echo " </td><td>{{\$client_group_name}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_due_invoices_balance');return false\">";
        echo  __("admin.mergefieldsinvoicesbalance");
        echo " </td><td>{{\$client_due_invoices_balance}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_custom_fields');return false\">";
        echo  __("admin.mergefieldscustomfieldsarray");
        echo "</td><td>{{\$client_custom_fields.1}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_custom_fields_by_name');return false\">";
        echo  __("admin.mergefieldscustomfieldsarray");
        echo "</td><td>{{\$client_custom_fields_by_name.0.name}}: 
            {{\$client_custom_fields_by_name.0.value}}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('client_status');return false\">";
        echo  __("admin.fieldsstatus");
        echo "</td><td>{{\$client_status}}</a></td></tr>\n</table><br />\n";
    }
    echo "<b>";
    echo  __("admin.mergefieldsother");
    echo "</b><br />\n<table>\n\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('company_name');return false\">";
    echo  __("admin.fieldscompanyname");
    echo "</td><td>{{\$company_name}}</a></td></tr>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('company_domain');return false\">";
    echo  __("admin.fieldsdomain");
    echo "</td><td>{{\$company_domain}}</a></td></tr>\n<tr><td width=\"150\"><a href=\"#\" onclick=\"insertMergeField('company_logo_url');return false\">";
    echo  __("admin.generallogourl");
    echo "</td><td>{{\$company_logo_url}}</a></td></tr>\n<tr>\n    <td width=\"150\">\n        <a href=\"#\" onclick=\"insertMergeField('company_tax_code');return false\">\n            ";
    echo  __("admin.taxconfigtaxCode");
    echo "        </a>\n    </td>\n    <td>{{\$company_tax_code}}</td>\n</tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('whmcs_url');return false\">";
    echo  __("admin.mergefieldswhmcsurl");
    echo "</td><td>{{\$whmcs_url}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('whmcs_link');return false\">";
    echo  __("admin.mergefieldswhmcslink");
    echo "</td><td>{{\$whmcs_link}}</a></td></tr>\n";
    if ($type == "admin") {
        echo "<tr><td><a href=\"#\" onclick=\"insertMergeField('whmcs_admin_url');return false\">";
        echo  __("admin.mergefieldswhmcsadminurl");
        echo "</td><td>{{\$whmcs_admin_url}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('whmcs_admin_link');return false\">";
        echo  __("admin.mergefieldswhmcsadminlink");
        echo "</td><td>{{\$whmcs_admin_link}}</a></td></tr>\n";
    }
    echo "<tr><td><a href=\"#\" onclick=\"insertMergeField('email_marketing_optin_url');return false\">";
    echo  __("admin.mergefieldsemailMarketingOptInUrl");
    echo "</td><td>{{\$email_marketing_optin_url}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('email_marketing_optout_url');return false\">";
    echo  __("admin.mergefieldsemailMarketingOptOutUrl");
    echo "</td><td>{{\$email_marketing_optout_url}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('signature');return false\">";
    echo  __("admin.mergefieldssignature");
    echo "</td><td>{{\$signature}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('date');return false\">";
    echo  __("admin.mergefieldsdate");
    echo "</td><td>{{\$date}}</a></td></tr>\n<tr><td><a href=\"#\" onclick=\"insertMergeField('time');return false\">";
    echo  __("admin.mergefieldstime");
    echo "</td><td>{{\$time}}</a></td></tr>\n</table><br />\n\n</td><td width=\"50%\" valign=\"top\">\n\n<b>";
    echo  __("admin.mergefieldscondisplay");
    echo "</b><br />\n";
    echo  __("admin.mergefieldscondisplay1");
    echo ":<br /><br />\n@if (\$ticket_department == \"";
    echo  __("admin.supportreqsales");
    echo "\")<br />\n";
    echo  __("admin.mergefieldscondisplay2");
    echo "<br />\n@else<br />\n";
    echo  __("admin.mergefieldscondisplay3");
    echo "<br />\n@endif<br /><br />\n\n<b>";
    echo  __("admin.mergefieldslooping");
    echo "</b><br />\n";
    echo  __("admin.mergefieldslooping1");
    echo ":<br /><br />\n@foreach (\$array_data as \$data)<br />\n{{\$data->option}}: 
    {{\$data->value}}<br />\n
    @endforeach\n\n</td></tr></table>\n\n</div>\n\n<br />\n";

@endphp
