    {{-- <script src="{{ Theme::asset('assets/libs/jquery/jquery.min.js') }}"></script> --}}
    <script src="{{ Theme::asset('assets/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/metismenu/metisMenu.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/simplebar/simplebar.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/node-waves/waves.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/select2/js/select2.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/pages/add-new-order.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/hideSidebar.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/login-form.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/navbar-responsive.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/auto-close-alert.js') }}"></script>
    <script src="{{ Theme::asset('assets/libs/bootstrap-switch-custom/bootstrap4-toggle.min.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/app.js') }}"></script>
    <script src="{{ Theme::asset('assets/js/search.js') }}"></script>
